[workspace]
resolver = "3"
members = [
	"alloc-traits",
	"exit-stack",
	"fill",
	"same-alloc",
	"static-alloc",
	"unsize",
	"without-alloc",
]

[workspace.package]
authors = ["Aurelia Molzer <5550310+197g@users.noreply.github.com>"]
license = "MIT OR Apache-2.0 OR Zlib"
repository = "https://github.com/197g/static-alloc"
readme = "Readme.md"
