[package]
name = "fill"
version = "0.1.1"
description = "Provides the Fill trait, an alternative to Extend for finite containers"
authors = ["Aurelia Molzer <5550310+197g@users.noreply.github.com>"]
edition = "2018"
license = "MIT OR Apache-2.0 OR Zlib"
documentation = "https://docs.rs/fill"
repository = "https://github.com/HeroicKatora/static-alloc"
readme = "Readme.md"
keywords = ["fill", "extend", "no-std", "no_std"]
categories = ["embedded", "no-std", "data-structures"]

[dependencies]
# None.

[features]
default = []

# Provide implementations for types in `alloc`
alloc = []

[[test]]
name = "alloc"
path = "tests/alloc.rs"
required-features = ["alloc"]

[package.metadata.docs.rs]
all-features = true
