[package]
name = "fill"
version = "0.1.1"
description = "Provides the Fill trait, an alternative to Extend for finite containers"
edition = "2018"
documentation = "https://docs.rs/fill"
readme = "Readme.md"
keywords = ["fill", "extend", "no-std", "no_std"]
categories = ["embedded", "no-std", "data-structures"]

authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
# None.

[features]
default = []

# Provide implementations for types in `alloc`
alloc = []

[[test]]
name = "alloc"
path = "tests/alloc.rs"
required-features = ["alloc"]

[package.metadata.docs.rs]
all-features = true
